### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by MADZEROPIE** [MADZEROPIE/Global_Search_Method#3]
Быстро:
- [x] Корректный подсчёт операционных характеристик для всех методов
- [x] Переписать CMake для правильной работы с OMP.

Не так быстро:
- [ ] Многомерный АГП с использованием разверток

Долго:
- [ ] Изменить генератор так, чтобы можно было комбинировать различные функции ограничений. (Подсказка: Использовать линейное растяжение.)
- [ ] Создать класс Application и убрать весь мусор из main
- [ ] Хранить результаты там, где надо, а не как выйдет.
- [ ] Автоматизировать всё (переписать файл юпитера(?))

Вечность:
- [ ] Рефакторинг. Давно пора.
